// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ../wire-runtime/src/test/proto/simple_message.proto
package com.squareup.wire.protos.simple;

import com.squareup.wire.Extension;
import com.squareup.wire.protos.foreign.ForeignMessage;

public final class Ext_simple_message {

  private Ext_simple_message() {
  }

  public static final Extension<ExternalMessage> fooext = Extension
      .int32Extending(ExternalMessage.class)
      .setName("squareup.protos.simple.fooext")
      .setTag(125)
      .buildRepeated();
  public static final Extension<ExternalMessage> barext = Extension
      .int32Extending(ExternalMessage.class)
      .setName("squareup.protos.simple.barext")
      .setTag(126)
      .buildOptional();
  public static final Extension<ExternalMessage> bazext = Extension
      .int32Extending(ExternalMessage.class)
      .setName("squareup.protos.simple.bazext")
      .setTag(127)
      .buildRequired();
  public static final Extension<ExternalMessage> nested_message_ext = Extension
      .messageExtending(SimpleMessage.NestedMessage.class, ExternalMessage.class)
      .setName("squareup.protos.simple.nested_message_ext")
      .setTag(128)
      .buildOptional();
  public static final Extension<ExternalMessage> nested_enum_ext = Extension
      .enumExtending(SimpleMessage.NestedEnum.class, ExternalMessage.class)
      .setName("squareup.protos.simple.nested_enum_ext")
      .setTag(129)
      .buildOptional();
  public static final Extension<ForeignMessage> j = Extension
      .int32Extending(ForeignMessage.class)
      .setName("squareup.protos.simple.j")
      .setTag(100)
      .buildOptional();
}
